### ISSUE TITLE
Release extendr 0.3.0

### ISSUE THREAD

**Issue by clauswilke** [extendr/extendr#215]
It's time to think about releasing extendr 0.3.0. There have been significant API changes since 0.2.0 and we should get them out. This issue will be to track any remaining items that need to be addressed before the release.

- [x] Update changelog (#208)
- [x] Improved API for calling R functions in packages (#216, see also #206)
- [x] Add `README` files to extendr crates (#217)
- [x] Fix or disable the `myvar` test (#211)

Please tag issues or add comments in the discussion for any additional items we should address before the next release.

**Comment by andy-thomason** [comment]
I'll set to when I next get some free time.

**Comment by multimeric** [comment]
It seems like all the above issues have been closed. Also, following discussion on the Discord, none of the main devs can identify any issues that urgently need attention before 0.3.0 release, so we're hoping to do it very soon based on the current state of the master branch.

**Comment by yutannihilation** [comment]
If we have bandwidth, I think we should polish the changelog. https://github.com/extendr/extendr/blob/master/CHANGELOG.md

Also, iirc, we have to publish libR-sys first, if the dev extendr depends on the dev libR-sys.

**Comment by multimeric** [comment]
Agreed. Can we do a more structured changelog with the same rough headings as https://keepachangelog.com/en/1.0.0/?

**Comment by Ilia-Kosenkov** [comment]
I marked all bullet points as completed in the original message and I close this issue because the `0.3.0` release has been published.
