### ISSUE TITLE
Switch CI to Github Actions

### ISSUE THREAD

**Issue by hobofan** [extendr/extendr#42]
From what I can gather on Discord there seems to be a consensus to switch to GH Actions (and away from TravisCI).

Some of the goals:
Build on
- [x] Linux (added in #44)
- [x] macOS (added in #44)
- [x] Windows (unfinished version added in #44)
- [ ] Automatic publish on pushed tags

Do you want to tackle this @CGMossa ? Otherwise I'd take a stab at it soon(-ish).

**Comment by CGMossa** [comment]
Please take a stab at it.


I tried to download `act` to test this locally, but it doesn't support
Windows.

**Comment by clauswilke** [comment]
@CGMossa FYI, there shouldn't be any need to test anything locally. Just drop a `.yaml` file into `.github/workflows` and see what happens when you push. If the build doesn't work, you amend the commit and try again. Can be a bit cumbersome, but that's the process everybody uses.

**Comment by clauswilke** [comment]
Build on windows works now. I've checked the box.

**Comment by yutannihilation** [comment]
> Automatic publish on pushed tags

I've never published a crate, but it seems it's as simple as just executing `cargo publish` with a secret. 

e.g. https://github.com/rust-windowing/winit/blob/master/.github/workflows/publish.yml

The question is, is it always the case that all the crates in this repo are published all together? Or, is there a chance that you want to publish only some of these with a small patch? If so, a better shell script might be needed.

**Comment by clauswilke** [comment]
I think it's best to keep think of all the crates in the extendr workspace as one unit that gets published all at the same time with the same version. Note that if we merge https://github.com/extendr/extendr/pull/50 there'll be one more crate in the workspace.

**Comment by yutannihilation** [comment]
I see. Then, maybe CI should check all the versions are the same?

**Comment by clauswilke** [comment]
Ah, yes, that sounds like a good idea. The versions and the dependency statements should all be the same. Otherwise you end up with issues such as this one: https://github.com/extendr/extendr/issues/28

**Comment by yutannihilation** [comment]
[cargo-workspace](https://github.com/pksunkara/cargo-workspaces) looks useful both for publishing and version check.

``` console
❯ cargo ws list --json
[
  {
    "name": "extendr-api",
    "version": "0.1.10",
    "location": "/home/yutani/repo/extendr/extendr-api",
    "private": false,
    "independent": false
  },
  {
    "name": "extendr-macros",
    "version": "0.1.10",
    "location": "/home/yutani/repo/extendr/extendr-macros",
    "private": false,
    "independent": false
  }
]

```

**Comment by clauswilke** [comment]
Oh yes, this looks very useful.

**Comment by andy-thomason** [comment]
This has been a stunning success.

Should we shift the automatic publish to another Issue? I'm keen to close as many issues as possible
to keep them fresh.

**Comment by clauswilke** [comment]
Yes, I think automatic publish can be deferred to some other time in the future, and in a different issue.

**Comment by clauswilke** [comment]
Closing this as GH actions are working now.
