### ISSUE TITLE
Adding random number generating 

### ISSUE THREAD

**Issue by CGMossa** [extendr/extendr#474]
Tasks:

- [ ] First include `R_ext/Random.h` in `libR-sys`, see extendr/libr-sys#123
- [ ] See if the manual guarding can be done solely by the bindgen result of this.
Otherwise provide a "safe" wrapper around these.
- [ ] Make a PR to amend `#[extendr]` with a `use_rng` tag or similar, that automatically inserts these state invocations. see #476 
- [ ] Extra: Ensure that the distribution functions work within rust and that they are "safe". Depends on whether extendr/libR-sys#124 gets merged.

Sources:

- [`cpp11` on random number generator](https://cpp11.r-lib.org/articles/converting.html#random-number-behavior)
- [Writing R Extensions on Random Numbers](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Random-numbers)
