### ISSUE TITLE
0.4.0 Release Thread

### ISSUE THREAD

**Issue by multimeric** [extendr/extendr#485]
There are a number of reasons we should make a new release asap. Prominently:

* It will fix the docs.rs build, which helps our online presence
* It adds support for arm64 Linux
* Windows toolchain changes (?)
* Other features that have been requested on the discord

# TODO

* [x] Vote on release
    * If you are a maintainer, please thumbs up or down this post. We will postpone the release if not enough people upvote or enough people downvote, acording to #448.
    * **Update**: we have quorum of 3 approving maintainers, and no disapprovals.
* [x] Fix changelog. PRs since last release are: https://github.com/extendr/extendr/pulls?q=is%3Apr+is%3Amerged+closed%3A%3E2022-05-20
* [x] Update crate metadata (version etc)

**Comment by Ilia-Kosenkov** [comment]
I would like this https://github.com/extendr/extendr/pull/480 to be reviewed (accepted or rejected) before this release.

**Comment by CGMossa** [comment]
Looks good. Will you also release a new `libR-sys`? I'll look in the publishing guides now..

**Comment by CGMossa** [comment]
I think, you need to publish a new version of `libR-sys` first, as per https://github.com/extendr/libR-sys/issues/115. 
Also that crate has no guide as to how to publish that crate.

**Comment by multimeric** [comment]
@yutannihilation would you mind doing the honours of publishing the crate please? I've made a new release but I don't have the appropriate permissions on crates.io.

**Comment by yutannihilation** [comment]
Maybe it's better to add all of you three as the owners?

@CGMossa @Ilia-Kosenkov 
I think you don't have the account on crates.io yet. I'll run `cargo owner` to add you so the invitation will be sent to you, if I remember correctly.

**Comment by multimeric** [comment]
Sounds good to me, thanks.

**Comment by multimeric** [comment]
Okay, so I will do the release instead then?

**Comment by yutannihilation** [comment]
Aw, it seems it requires an account registered on crates.io. 

```
❯ cargo owner --add Ilia-Kosenkov extendr-api
    Updating crates.io index
error: failed to invite owners to crate `extendr-api` on registry at https://crates.io

Caused by:
  the remote server responded with an error: could not find user with login `Ilia-Kosenkov`
```

@Ilia-Kosenkov @CGMossa 
Could you ping me after you create your account?

**Comment by yutannihilation** [comment]
@multimeric 
> Okay, so I will do the release instead then?

Yes, I think you are more appropriate than me as you are handling the release process.

**Comment by CGMossa** [comment]
@yutannihilation I've done it, I guess. It ties crates-io with github.com account.

**Comment by Ilia-Kosenkov** [comment]
Done @yutannihilation

**Comment by yutannihilation** [comment]
Thanks, invited.
