### ISSUE TITLE
Release version 0.2.0

### ISSUE THREAD

**Issue by clauswilke** [extendr/extendr#68]
I'd like to release a version 0.2.0 that provides a minimally viable product on all platforms. Below is the checklist for the release. If I'm forgetting anything, please let me know in the comments.

* [x] Address all issues/PRs in the 0.2.0 milestone
* [x] Finalize and release libR-sys 0.2.0 (https://github.com/extendr/libR-sys/issues/20)
* [x] ~~Fix `bump.sh` and `publish.sh` (#70)~~ (see #82)
* [x] Bump libR-sys dependency to latest version
* [x] Remove any patch_crates.io statements from top-level `Cargo.toml`
* [x] Bump version to 0.2.0
* [x] Bump version number in changelog 
* [x] ~~Verify that all crates in the workspace have the same version and the same extendr version dependencies~~ (see #82)
* [x] Tag release on github
* [x] Release to crates.io

**Comment by clauswilke** [comment]
@andy-thomason Given the amount of changes we're making right now, and considering that the resulting crate will likely be the first minimally usable product, should the next release be 0.2.0?

**Comment by andy-thomason** [comment]
I would like to get the updated docs and cleaner API into the release.

There are some minor breaking changes as I've dropped rust type names in favour
of "integer", "logical", "numeric", "character" where possible as R users will
be more familiar with these.

The docs are looking much better now, although not visible in docs.rs until we publish.

**Comment by clauswilke** [comment]
Agreed. In addition, I'd like to merge #93, since it allows us to use the module macro on Windows.

**Comment by clauswilke** [comment]
@andy-thomason I have gone over the open issues and added relevant ones to the 0.2 milestone:
https://github.com/extendr/extendr/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.2.0
Could you add any issues I haven't added that you think we should address before a release? In this way we can keep track of where we are.

Also, I think for 0.2.0 we should focus on API design, overall architecture, and basic functionality, since it'll probably be around for a while. We can add documentation and convenience functions later.

**Comment by andy-thomason** [comment]
I think we are good to go on 0.2.0

Feel free to bump and publish, or I will go ahead on Monday.

**Comment by clauswilke** [comment]
Ok, I've made a release. Let's hope it's all correct. Currently testing with rextendr.

**Comment by clauswilke** [comment]
Things seem to be working fine.

**Comment by andy-thomason** [comment]
Tada!
